# This is a basic workflow to help you get started with Actions

name: Annoucement Notifier
on: 
  discussion:
    types: [created, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  notify:
    if: ${{ github.event.discussion.category.name == 'Announcements' }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    env:
      TRIGGER: "${{github.event_name}}"
      DELIVERY: "${{github.sha}}"
      WEBHOOK: ${{ secrets.ANNOUNCEMENT_WEBHOOK }}
      GITHUB_EVENT: "${{ toJson(github.event) }}"
    steps:
      - name: Webhook Notifier
        run: |
          'curl --location --request POST "${WEBHOOK}" --header "x-github-event: $TRIGGER" --header "x-github-delivery: $DELIVERY" --header "Content-Type: application/json" --data-raw "$(echo "$GITHUB_EVENT"|jq -c .)"'
