# This is a basic workflow to help you get started with Actions

name: Annoucement Notifier
on: 
  discussion:
    types: [created, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  notify:
    if: ${{ github.event.discussion.category.name == 'Announcements' }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      TRIGGER: "${{ github.event_name }}"
      DELIVERY: "${{ github.sha }}"
      WEBHOOK: ${{ secrets.ANNOUNCEMENT_WEBHOOK }}
      GITHUB_EVENT: "${{ toJson(github.event) }}"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Webhook Notifier
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.ANNOUNCEMENT_WEBHOOK }}
          headers: '{"Content-Type": "application/json", "X-GitHub-Delivery": $DELIVERY, "X-GitHub-Event": $TRIGGER }'
          body: ${{ toJson(github.event) }}
