# This is a basic workflow to help you get started with Actions

name: General Discussion Notifier

on: 
  discussion:
    types: created

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: ${{ github.event.discussion.category.name == 'General' }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Webhook Notifier
        # You may pin to the exact commit or the version.
        # uses: Netail/webhook-notifier@137c609e90bb9c07c0434e8093a6550795ba9d37
        uses: jasongitmail/fast-webhook@v1.1.4
        with:
          # The webhook URL to send the request to.
          url: ${{ secrets.GENERAL_WEBHOOK }}
          # The stringified JSON body to be sent, if any.
          json: ${{ github.event.discussion }}
